config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'todo#index'
  resources :todo

  # get :todo#index


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todolist.rb
class Todolist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
   
    def index
        @todo  = Todolist.all
        
    end

    def show
        @todo = Todolist.find(params[:id])
    end

    def new
        @todo = Todolist.new
    end


    def create 
        @todo = Todolist.new(params.require(:todo).permit(:description))
        if @todo.save
            redirect_to todo_index_path
        else
            render :new
        end
    end

    def update 
        @todo = Todolist.find(params[:id]).update(params.require(:todo).permit(:description))
        if @todo
            redirect_to todo_index_path
        else
            render :update
        end
    end


    def edit
        @todo = Todolist.find(params[:id])
    end

    def destroy
        @todo=Todolist.find(params[:id]).delete
        redirect_to todo_index_path
    end
    

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' : 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track' : 'reload' %>
    <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" integrity="sha512-Ez0cGzNzHR1tYAv56860NLspgUGuQw16GiOOp/I2LuTmpSK9xDXlgJz3XN4cnpXWDmkNBKXR/VDMTCnAaEooxA==" crossorigin="anonymous" referrerpolicy="no-referrer" /> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/edit.html.erb
<div class="navbar bg-info text-light">
    
        <h1 ><a href="/todo" class="nav-link ">Mero Task</a></h1>
</div>





<%= form_for :todo, url:{ action: :update }, method: :put do |f| %>
  <div class = "container">
    <div class = "row ">
      <div class = " d-flex justify-content-center   ">
        <div class = "col-md-4 border shadow rounded p-5 m-5">
          <div class = "form-group ">

            <%= f.label "Update My Task", :class =>"form-label text-danger mb-0"  %>
            <hr>
            <%= f.text_field :description, :class =>"form-control my-4" , required: true %>
            <%= f.submit "Correct", :class =>"btn btn-outline-primary my-3" %>
            <button class = "btn btn-danger">Cancel</button>

          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

<div class = "fixed-bottom d-flex justify-content-center text-light bg-dark">Developed by &copy; Mukesh Mahara</div>

app/views/todo/index.html.erb
<div class="navbar bg-info text-light">
    
        <h1 ><a href="/todo" class="nav-link ">Mero Task</a></h1>
</div>

<div class = "container">

    <%= link_to "Add Your Daily Task",new_todo_path, :class => "btn btn-outline-success my-4 w-100"  %>

    <table class = "table border table-hover shadow table-striped text-center">
        <tr>
            <th>Created At</th>
            <th>Task</th>
            <th>Status</th>
            <th>Option</th>
        </tr>

          <% @todo.each do |f| %>
            <tr>

                
                <td><%=f.created_at%></td>
                <td > <%=f.description%> </td>
                <td>Completed</td>
                <td> 
                    <%=link_to "",todo_path(f.id), :class =>"btn btn-outline-secondary fa fa-eye tooltips","data-toggle" =>"tooltip", "data-placement" =>"top", 'title' => "view"%>
                    <%=link_to "", edit_todo_path(f.id), :class =>"btn btn-outline-info fa fa-edit tooltips","data-toggle" =>"tooltip", "data-placement" =>"top", 'title' => "edit"%>
                    <%=link_to "", todo_path(f.id), method: :delete, data:{confirm: 'Are you sure ?'}, :class =>"btn btn-outline-danger fa fa-trash-alt tooltips","data-toggle" =>"tooltip", "data-placement" =>"top", 'title' => "delete"%>
                </td>


            </tr>
        <% end %>

    </table>
        


    
</div>

<div class = "fixed-bottom d-flex justify-content-center text-light bg-dark">Developed by &copy; Mukesh Mahara</div>

app/views/todo/new.html.erb
<div class="navbar bg-info text-light">
    
        <h1 ><a href="/todo" class="nav-link ">Mero Task</a></h1>
</div>



<%= form_for :todo, url:{ action: :create } do |f| %>
  <div class = "container my-4">
    <div class = "row ">
      <div class = " d-flex justify-content-center ">
        <div class = "col-md-4">
          <div class = "form-group border p-4 rounded shadow">

            <%= f.label "Task", :class =>"form-label"%>
            <%= f.text_field :description, :class =>"form-control", required: true %>
            <%= f.submit "Add Task", :class =>"btn btn-outline-primary my-3" %>
            <a href="/todo" class="btn btn-danger">Cancel</a>
          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

<div class = "fixed-bottom d-flex justify-content-center text-light bg-dark">Developed by &copy; Mukesh Mahara</div>

app/views/todo/show.html.erb
<div class="navbar bg-info text-light">
    
        <h1 ><a href="/todo" class="nav-link ">Mero Task</a></h1>
</div>

<div class = "container">

    <div class = "row">
        <div class="d-flex justify-content-center my-5">

            <div class = "col-md-4">
               <ul><li> <%=@todo.description%></li></ul>
                <div class="mx-3">
                 <%= link_to "Add Your Daily Task",new_todo_path, :class => "btn btn-outline-success my-4 "  %>
               <a href="/todo" class="btn btn-danger  ">back</a></div>

            </div>
        
        </div>
    </div>

</div>